[package]
name = "UefiVariablePolicyLibRust"
version = "0.1.0"
authors = ["Bret Barkelew <bret.barkelew@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fmp_authentication_lib_pkcs7_rust"
crate-type = ["staticlib"]

# the profile used for `cargo build`
[profile.dev]
panic = "abort" # disable stack unwinding on panic

# the profile used for `cargo build --release`
[profile.release]
panic = "abort" # disable stack unwinding on panic

[dependencies]
r-efi = "2.1.0"
